/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    AccuracyVisualizerChip: typeof import('./src/components/AccuracyVisualizerChip.vue')['default']
    CarFoundButton: typeof import('./src/components/CarFoundButton.vue')['default']
    CheckButton: typeof import('./src/components/CheckButton.vue')['default']
    CompassNorthOutlineIcon: typeof import('./src/components/CompassNorthOutlineIcon.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    ReleaseNotesItem: typeof import('./src/components/ReleaseNotesItem.vue')['default']
    ResetAppStateDialog: typeof import('./src/components/ResetAppStateDialog.vue')['default']
    SetCarPositionButton: typeof import('./src/components/SetCarPositionButton.vue')['default']
    SwitchThemeListItem: typeof import('./src/components/SwitchThemeListItem.vue')['default']
  }
}
