/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    AccuracyVisualizerChip: typeof import('./src/components/AccuracyVisualizerChip.vue')['default']
    CarFoundBtn: typeof import('./src/components/CarFoundBtn.vue')['default']
    CheckBtn: typeof import('./src/components/CheckBtn.vue')['default']
    CompassNorthOutlineIcon: typeof import('./src/components/CompassNorthOutlineIcon.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    ResetAppStateDialog: typeof import('./src/components/ResetAppStateDialog.vue')['default']
    SetCarPositionBtn: typeof import('./src/components/SetCarPositionBtn.vue')['default']
    SwitchThemeListItem: typeof import('./src/components/SwitchThemeListItem.vue')['default']
  }
}
